# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CODE_ME
email: omnyx2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  안녕하세요, 저의 블로그 CODE ME는 제가 공부한 개발자적인 자료와 인문학적 자료를 정리하기 위해 만들었습니다.
  시간나시면 천천히 들러서 읽어주시면 좋겠습니다. 현재 GIST에 재학중인 4학년입니다.  \\ 
  감사합니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown

include:
  - _pages

#colletions
collections:
  studypage:
    output: true
    permalink: /study/:path/
  programming:
    output: true
    permalink: /:collection/:path/
  math:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  references:
    output: true
    permalink: /:collection/:path/
  refspage:
    output: true
    permalink: /references/:path/

#comments
disqus: code-me

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      read_time: true
  #study
  - scope:
      path: "_studypage"
      type: studypage
    values:
      layout: post_relate
      read_time: true
      comments: true
  - scope:
      path: "_programming"
      type: programming
    values:
      layout: post_relate
      read_time: true
      comments: true
  - scope:
      path: "_math"
      type: math
    values:
      layout: post_relate
  #references
  - scope:
      path: "_refspage"
      type: refspage
    values:
      layout: post_relate
      read_time: true
      comments: true
